export const QUIZ_SEED = [
  {
    text: 'Что выведет `console.log(typeof null)`?',
    options: ['"null"', '"object"', '"undefined"', '"number"'],
    correctIndex: 1,
    category: 'types',
    difficulty: 'easy',
  },
  {
    text: 'Какой результат у выражения `[] + []`?',
    options: ['[]', '0', '"" (пустая строка)', 'undefined'],
    correctIndex: 2,
    category: 'coercion',
    difficulty: 'medium',
  },
  {
    text: 'Что делает оператор `===`?',
    options: [
      'Сравнивает только значения с приведением типов',
      'Сравнивает значения и типы без приведения',
      'Присваивает значение',
      'Проверяет ссылочное равенство только для объектов',
    ],
    correctIndex: 1,
    category: 'operators',
    difficulty: 'easy',
  },
  {
    text: 'Какой метод массива НЕ мутирует исходный массив?',
    options: ['push', 'splice', 'map', 'sort'],
    correctIndex: 2,
    category: 'arrays',
    difficulty: 'easy',
  },
  {
    text: 'Что такое замыкание (closure) в JavaScript?',
    options: [
      'Способ закрыть вкладку браузера',
      'Функция вместе с лексическим окружением, в котором она была создана',
      'Синтаксис для классов',
      'Механизм сборки мусора',
    ],
    correctIndex: 1,
    category: 'functions',
    difficulty: 'medium',
  },
  {
    text: 'Что вернёт `Promise.resolve(1).then(x => x + 1)`?',
    options: [
      '1',
      'Promise, который resolve-ится в 2',
      '2',
      'undefined',
    ],
    correctIndex: 1,
    category: 'async',
    difficulty: 'medium',
  },
  {
    text: 'Как правильно объявить константу?',
    options: ['var PI = 3.14', 'let PI = 3.14', 'const PI = 3.14', 'constant PI = 3.14'],
    correctIndex: 2,
    category: 'basics',
    difficulty: 'easy',
  },
  {
    text: 'Что делает `Object.freeze(obj)`?',
    options: [
      'Удаляет объект из памяти',
      'Делает объект неизменяемым (shallow)',
      'Клонирует объект',
      'Сериализует объект в JSON',
    ],
    correctIndex: 1,
    category: 'objects',
    difficulty: 'medium',
  },
  {
    text: 'Какой порядок выполнения: sync, microtasks, macrotasks?',
    options: [
      'macrotasks → microtasks → sync',
      'sync → microtasks → macrotasks',
      'microtasks → sync → macrotasks',
      'sync → macrotasks → microtasks',
    ],
    correctIndex: 1,
    category: 'event-loop',
    difficulty: 'hard',
  },
  {
    text: 'Что такое hoisting?',
    options: [
      'Поднятие объявлений var/function в начало области видимости',
      'Оптимизация V8',
      'Способ импорта модулей',
      'Удаление неиспользуемого кода',
    ],
    correctIndex: 0,
    category: 'scope',
    difficulty: 'medium',
  },
  {
    text: 'Чем `let` отличается от `var`?',
    options: [
      'let имеет блочную область видимости, var — функциональную',
      'var нельзя переопределить',
      'let работает только в strict mode',
      'Ничем, это синонимы',
    ],
    correctIndex: 0,
    category: 'scope',
    difficulty: 'easy',
  },
  {
    text: 'Что вернёт `Array.isArray({})`?',
    options: ['true', 'false', 'undefined', 'TypeError'],
    correctIndex: 1,
    category: 'arrays',
    difficulty: 'easy',
  },
  {
    text: 'Для чего нужен `async/await`?',
    options: [
      'Для синхронного выполнения только setTimeout',
      'Для удобной работы с Promise в «линейном» стиле',
      'Для объявления переменных',
      'Для CSS-анимаций',
    ],
    correctIndex: 1,
    category: 'async',
    difficulty: 'easy',
  },
  {
    text: 'Что делает метод `JSON.parse`?',
    options: [
      'Превращает объект в JSON-строку',
      'Парсит JSON-строку в значение JavaScript',
      'Валидирует HTML',
      'Копирует объект глубоко',
    ],
    correctIndex: 1,
    category: 'json',
    difficulty: 'easy',
  },
  {
    text: 'Какое значение у `this` в стрелочной функции?',
    options: [
      'Всегда window/global',
      'Берётся из лексического окружения (не свой this)',
      'Всегда undefined',
      'Указывает на саму функцию',
    ],
    correctIndex: 1,
    category: 'functions',
    difficulty: 'medium',
  },
];
